### ISSUE TITLE
Allure не генерирует отчёты

### ISSUE THREAD

**Issue by kokokokokomi** [komisuomi/AQA_9_reports#4]
Allure не генерирует отчёты с результатами автотестов.

**Шаги для воспроизведения:**

- Запустить файл [app-card-delivery.jar](https://github.com/netology-code/aqa-homeworks/blob/aqa4/patterns/app-card-delivery.jar) в командной строке или терминале IDEA. 
Исполняемая команда: ` java -jar artifacts/app-card-delivery.jar`.
- Запустить в командной строке команду `gradlew clean test allureReport`.

**Ожидаемый результат:**
Происходит прогон автотестов, результаты генерируются в html-файле, который можно найти в папке build.

**Фактический результат:**
Тесты не запускаются. Формируется ошибка с текстом:
`could not initialize class org.codehaus.groovy.reflection.reflection cache`

**Сетевое окружение:**
Windows 10, **Java 11**, браузер Google Chrome версия 87.0.4280.66.

**Вероятные пути решения:**

- Использовать Java 11 версии (такая ошибка часто появляется в проектах, выполненных на Java 14 и 15). В моём случае проект изначально был сделан на Java 11.
- Вручную изменить версию gradle: gradle/wrapper/gradle-wrapper.properties изменить на gradle-6.4.1-bin.zip.

Второй пункт позволил запустить все автотесты командой `gradlew clean test allureReport`. Однако в папке build так и не появилось нужного файла (имеется только стандартный отчёт gradle).

**Comment by andrew-pahomov** [comment]
Добрый день, Сергей.     
После команды `gradlew clean test allureReport` выполните `gradlew downloadAllure`, а потом `gradlew allureServe`

**Comment by kokokokokomi** [comment]
Благодарю за помощь, всё получилось.
![allure](https://user-images.githubusercontent.com/70074580/102489072-0cd0ce80-407e-11eb-9d91-0d0b37d7833c.png)
